export type AdminDisputeStatus = "OPEN" | "RESOLVED" | "REJECTED";
export type EscalationLevel = "NONE" | "SOFT" | "HARD";

export interface AdminDisputeQueueItem { disputeId: string; bookingId: string; status: AdminDisputeStatus; raisedByRole: "USER" | "CREATOR"; reasonSummary: string; escalationLevel: EscalationLevel; createdAt: string; escalatedAt: string | null; resolvedAt: string | null; booking: null | { bookingReference: string | null; serviceTitle: string; status: string }; }
export interface AdminDisputeList { disputes: AdminDisputeQueueItem[]; pagination: { page: number; limit: number; total: number }; }
export interface AdminDisputeDetail { dispute: { disputeId: string; status: AdminDisputeStatus; reason: string; raisedByRole: "USER" | "CREATOR"; slaHours: number; escalationLevel: EscalationLevel; escalatedAt: string | null; signals: string[]; createdAt: string; updatedAt: string; resolution: null | { action: string; note: string | null; resolvedAt: string }; allowedActions: string[] }; booking: null | { bookingReference: string | null; serviceTitle: string; status: string; currency: string; paymentMethod: string | null; totalAmount: number; serviceAmount: number; customerFeeAmount: number; creatorCommissionAmount: number; creatorNetAmount: number; createdAt: string; completedAt: string | null; terminatedAt: string | null; expiresAt: string; settlementEligibleAt: string | null }; payment: null | { paymentReference: string; status: string; amount: number; currency: string; method: string; authorizedAt: string | null; releasedAt: string | null; capturedAt: string | null }; reservation: null | { reservationReference: string; status: string; amount: number; currency: string; authorizedAt: string | null; releasedAt: string | null; releaseCause: string | null; capturedAt: string | null; captureCause: string | null }; escrow: null | { allocationReference: string; status: string; serviceAmount: number; customerFeeAmount: number; creatorCommissionAmount: number; creatorNetAmount: number; totalAmount: number; currency: string; allocatedAt: string | null }; settlement: null | { settlementReference: string; status: string; amount: number; currency: string; settledAt: string | null }; refund: null | { refundReference: string; status: string; amount: number; currency: string; createdAt: string; updatedAt: string }; }
export interface AdminDisputeFilters { page: number; limit: number; status?: AdminDisputeStatus; escalationLevel?: EscalationLevel; }
export type InvestigationTarget = "CUSTOMER" | "CREATOR" | "BOTH";
export type DirectEvidenceAudience = "ADMIN_ONLY" | "CUSTOMER" | "CREATOR" | "BOTH";
export interface AdminInvestigationEvidence { evidenceReference:string; source:"CUSTOMER"|"CREATOR"|"ADMIN"; type:"IMAGE"|"DOCUMENT"; audience:DirectEvidenceAudience|null; url:string; fileName:string; mimeType:string; fileSize:number; note:string|null; createdAt:string; }
export interface AdminInvestigationSubmission { submissionReference:string; branch:"CUSTOMER"|"CREATOR"; kind:string; text:string|null; evidence:Array<{evidenceReference:string;type:string;url:string;fileName:string;mimeType:string;fileSize:number;caption:string|null}>; createdAt:string; sharedWithCounterpartyAt:string|null; }
export interface AdminDisputeInvestigation { dispute:{disputeId:string;status:AdminDisputeStatus;investigation:{customerInput:{state:"OPEN"|"CLOSED";changedAt:string|null};creatorInput:{state:"OPEN"|"CLOSED";changedAt:string|null}}}; customerBranch:AdminInvestigationSubmission[]; creatorBranch:AdminInvestigationSubmission[]; directEvidence:AdminInvestigationEvidence[]; adminEvidence:AdminInvestigationEvidence[]; customerAdminRequests:Array<{requestReference:string;target:"CUSTOMER";text:string;createdAt:string}>; creatorAdminRequests:Array<{requestReference:string;target:"CREATOR";text:string;createdAt:string}>; sharedAdminRequests:Array<{requestReference:string;target:"BOTH";text:string;createdAt:string}>; context:{ customer:null|{userId:string;displayName:string;avatar:string|null;status:string;governanceState:string;abuseScore:number;userCooldownUntil:string|null;creatorCooldownUntil:string|null;profileStatus:string|null}; creator:null|{userId:string;displayName:string;avatar:string|null;status:string;governanceState:string;abuseScore:number;userCooldownUntil:string|null;creatorCooldownUntil:string|null;creatorProfile:null|{slug:string;status:string;categories:string[];location:string;currency:string;languages:string[];rating:number;reviewCount:number}}; booking:null|{bookingReference:string|null;status:string;paymentStatus:string;serviceTitle:string;durationMinutes:number;price:number;currency:string;createdAt:string;completedAt:string|null;terminatedAt:string|null;expiresAt:string;slots:Array<{startTime:string;endTime:string;status:string}>;serviceSnapshot:null|{serviceId:string;title:string;description:string;durationMinutes:number;price:number;currency:string;media:string[]}}; chat:{messages:Array<{senderId:string;senderRole:string;type:string;message:string;aiFlags:string[];isDeleted:boolean;deletedAt:string|null;createdAt:string;attachment:null|{url:string;fileName:string;mimeType:string;fileSize:number;resourceType:string}}>;limit:number}; reviews:Array<{role:string;rating:number;comment:string|null;reportFlag:boolean;isFlagged:boolean;createdAt:string}>; moderation:Array<{severity:string;reasons:string[];reviewed:boolean;createdAt:string}>; previousDisputes:{customer:Array<{disputeId:string;status:string;createdAt:string}>;creator:Array<{disputeId:string;status:string;createdAt:string}>};history:Array<{action:string;entityType:string;createdAt:string}>}; limit:number; }
export type FindingSubject="CUSTOMER"|"CREATOR"|"BOTH"; export type FindingConclusion="SUPPORTED"|"NOT_SUPPORTED"|"INCONCLUSIVE"; export type ParticipantOutcome="NO_ADVERSE_FINDING"|"ADVERSE_FINDING"|"MIXED"|"INCONCLUSIVE";
export interface AdminDisputeInvestigation { findings:Array<{findingReference:string;subject:FindingSubject;category:string;conclusion:FindingConclusion;summary:string;createdAt:string}>; finalDecision:null|{customerOutcome:ParticipantOutcome;customerSummary:string;creatorOutcome:ParticipantOutcome;creatorSummary:string;summary:string;financialReviewRequired:boolean;governanceReviewRequired:boolean;finalizedAt:string}; }
