import axios from "axios";
import { useCallback, useEffect, useState } from "react";
import { addDisputeFinding, closeDisputeNoAction, finalizeDisputeInvestigation, getAdminDispute, getAdminDisputeInvestigation, getAdminDisputes, requestDisputeInfo, setDisputeInput, shareDisputeSubmission, uploadAdminDisputeEvidence } from "./api";
import type { AdminDisputeDetail, AdminDisputeFilters, AdminDisputeInvestigation, AdminDisputeList, AdminDisputeStatus, DirectEvidenceAudience, EscalationLevel, InvestigationTarget } from "./types";
type State = "loading" | "ready" | "error";
function message(error: unknown, fallback: string) { if (axios.isAxiosError(error) && typeof error.response?.data?.message === "string") return error.response.data.message; return fallback; }
export function useAdminDisputes(disputeId?: string) {
  const [filters, setFilters] = useState<AdminDisputeFilters>({ page: 1, limit: 25 }); const [list, setList] = useState<AdminDisputeList | null>(null); const [detail, setDetail] = useState<AdminDisputeDetail | null>(null); const [investigation,setInvestigation]=useState<AdminDisputeInvestigation|null>(null); const [listState, setListState] = useState<State>("loading"); const [detailState, setDetailState] = useState<State>("loading"); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const [tick, setTick] = useState(0); const refresh = useCallback(() => setTick((value) => value + 1), []);
  useEffect(() => { if (disputeId) return; let cancelled = false; void (async () => { setListState("loading"); setError(null); try { const next = await getAdminDisputes(filters); if (!cancelled) { setList(next); setListState("ready"); } } catch (requestError) { if (!cancelled) { setError(message(requestError, "Could not load disputes.")); setListState("error"); } } })(); return () => { cancelled = true; }; }, [disputeId, filters, tick]);
  useEffect(() => { if (!disputeId) return; let cancelled = false; void (async () => { setDetailState("loading"); setError(null); try { const [next,workspace] = await Promise.all([getAdminDispute(disputeId),getAdminDisputeInvestigation(disputeId)]); if (!cancelled) { setDetail(next);setInvestigation(workspace); setDetailState("ready"); } } catch (requestError) { if (!cancelled) { setError(message(requestError, "Could not load this dispute.")); setDetailState("error"); } } })(); return () => { cancelled = true; }; }, [disputeId, tick]);
  const closeNoAction = useCallback(async (note: string) => { if (!disputeId || pending) return false; setPending(true); setError(null); try { await closeDisputeNoAction(disputeId, note); refresh(); return true; } catch (requestError) { setError(message(requestError, "We could not confirm that the dispute was closed. Authoritative dispute data was refreshed; do not retry automatically.")); refresh(); return false; } finally { setPending(false); } }, [disputeId, pending, refresh]);
  const mutate=useCallback(async(action:()=>Promise<unknown>)=>{if(pending)return false;setPending(true);setError(null);try{await action();refresh();return true;}catch(requestError){setError(message(requestError,"The server did not confirm the action. Investigation data was refreshed."));refresh();return false;}finally{setPending(false);}},[pending,refresh]);
  return { filters, setStatus: (status?: AdminDisputeStatus) => setFilters((current) => ({ ...current, status, page: 1 })), setEscalationLevel: (escalationLevel?: EscalationLevel) => setFilters((current) => ({ ...current, escalationLevel, page: 1 })), setPage: (page: number) => setFilters((current) => ({ ...current, page })), list, detail, investigation, listState, detailState, error, pending, refresh, closeNoAction, setInput:(role:"CUSTOMER"|"CREATOR",state:"OPEN"|"CLOSED")=>disputeId?mutate(()=>setDisputeInput(disputeId,role,state)):Promise.resolve(false), requestInfo:(target:InvestigationTarget,text:string)=>disputeId?mutate(()=>requestDisputeInfo(disputeId,target,text)):Promise.resolve(false), share:(reference:string)=>disputeId?mutate(()=>shareDisputeSubmission(disputeId,reference)):Promise.resolve(false), uploadEvidence:(type:"IMAGE"|"DOCUMENT",file:File,audience:DirectEvidenceAudience,note:string)=>disputeId?mutate(()=>uploadAdminDisputeEvidence(disputeId,type,file,audience,note)):Promise.resolve(false), addFinding:(payload:{subject:"CUSTOMER"|"CREATOR"|"BOTH";category:string;conclusion:"SUPPORTED"|"NOT_SUPPORTED"|"INCONCLUSIVE";summary:string})=>disputeId?mutate(()=>addDisputeFinding(disputeId,payload)):Promise.resolve(false), finalize:(payload:{customerOutcome:string;customerSummary:string;creatorOutcome:string;creatorSummary:string;summary:string;financialReviewRequired:boolean;governanceReviewRequired:boolean})=>disputeId?mutate(()=>finalizeDisputeInvestigation(disputeId,payload)):Promise.resolve(false) };
}
