// frontend/src/constants/timezones.ts

export const TIMEZONES = [
  // Asia
  { value: "Asia/Kolkata", label: "India - Mumbai / Delhi (UTC+05:30)" },
  { value: "Asia/Kathmandu", label: "Nepal - Kathmandu (UTC+05:45)" },
  { value: "Asia/Colombo", label: "Sri Lanka - Colombo (UTC+05:30)" },
  { value: "Asia/Dubai", label: "UAE - Dubai (UTC+04:00)" },
  { value: "Asia/Riyadh", label: "Saudi Arabia - Riyadh (UTC+03:00)" },
  { value: "Asia/Karachi", label: "Pakistan - Karachi (UTC+05:00)" },
  { value: "Asia/Dhaka", label: "Bangladesh - Dhaka (UTC+06:00)" },
  { value: "Asia/Bangkok", label: "Thailand - Bangkok (UTC+07:00)" },
  { value: "Asia/Ho_Chi_Minh", label: "Vietnam - Ho Chi Minh City (UTC+07:00)" },
  { value: "Asia/Jakarta", label: "Indonesia - Jakarta (UTC+07:00)" },
  { value: "Asia/Singapore", label: "Singapore (UTC+08:00)" },
  { value: "Asia/Kuala_Lumpur", label: "Malaysia - Kuala Lumpur (UTC+08:00)" },
  { value: "Asia/Manila", label: "Philippines - Manila (UTC+08:00)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong (UTC+08:00)" },
  { value: "Asia/Shanghai", label: "China - Shanghai (UTC+08:00)" },
  { value: "Asia/Taipei", label: "Taiwan - Taipei (UTC+08:00)" },
  { value: "Asia/Seoul", label: "South Korea - Seoul (UTC+09:00)" },
  { value: "Asia/Tokyo", label: "Japan - Tokyo (UTC+09:00)" },
  { value: "Asia/Jerusalem", label: "Israel - Jerusalem (UTC+02:00)" },
  { value: "Asia/Tbilisi", label: "Georgia - Tbilisi (UTC+04:00)" },
  { value: "Asia/Baku", label: "Azerbaijan - Baku (UTC+04:00)" },
  { value: "Asia/Yerevan", label: "Armenia - Yerevan (UTC+04:00)" },

  // Europe
  { value: "Europe/London", label: "United Kingdom - London (UTC±00:00)" },
  { value: "Europe/Dublin", label: "Ireland - Dublin (UTC±00:00)" },
  { value: "Europe/Paris", label: "France - Paris (UTC+01:00)" },
  { value: "Europe/Berlin", label: "Germany - Berlin (UTC+01:00)" },
  { value: "Europe/Amsterdam", label: "Netherlands - Amsterdam (UTC+01:00)" },
  { value: "Europe/Brussels", label: "Belgium - Brussels (UTC+01:00)" },
  { value: "Europe/Madrid", label: "Spain - Madrid (UTC+01:00)" },
  { value: "Europe/Rome", label: "Italy - Rome (UTC+01:00)" },
  { value: "Europe/Vienna", label: "Austria - Vienna (UTC+01:00)" },
  { value: "Europe/Zurich", label: "Switzerland - Zurich (UTC+01:00)" },
  { value: "Europe/Prague", label: "Czech Republic - Prague (UTC+01:00)" },
  { value: "Europe/Warsaw", label: "Poland - Warsaw (UTC+01:00)" },
  { value: "Europe/Bucharest", label: "Romania - Bucharest (UTC+02:00)" },
  { value: "Europe/Budapest", label: "Hungary - Budapest (UTC+01:00)" },
  { value: "Europe/Copenhagen", label: "Denmark - Copenhagen (UTC+01:00)" },
  { value: "Europe/Helsinki", label: "Finland - Helsinki (UTC+02:00)" },
  { value: "Europe/Stockholm", label: "Sweden - Stockholm (UTC+01:00)" },
  { value: "Europe/Oslo", label: "Norway - Oslo (UTC+01:00)" },
  { value: "Europe/Lisbon", label: "Portugal - Lisbon (UTC±00:00)" },
  { value: "Europe/Athens", label: "Greece - Athens (UTC+02:00)" },
  { value: "Europe/Istanbul", label: "Turkey - Istanbul (UTC+03:00)" },

  // Russia
  { value: "Europe/Moscow", label: "Russia - Moscow (UTC+03:00)" },
  { value: "Asia/Yekaterinburg", label: "Russia - Yekaterinburg (UTC+05:00)" },
  { value: "Asia/Krasnoyarsk", label: "Russia - Krasnoyarsk (UTC+07:00)" },
  { value: "Asia/Irkutsk", label: "Russia - Irkutsk (UTC+08:00)" },
  { value: "Asia/Vladivostok", label: "Russia - Vladivostok (UTC+10:00)" },

  // North America
  { value: "America/New_York", label: "USA - New York (UTC-05:00)" },
  { value: "America/Chicago", label: "USA - Chicago (UTC-06:00)" },
  { value: "America/Denver", label: "USA - Denver (UTC-07:00)" },
  { value: "America/Phoenix", label: "USA - Phoenix (UTC-07:00)" },
  { value: "America/Los_Angeles", label: "USA - Los Angeles (UTC-08:00)" },
  { value: "Pacific/Honolulu", label: "USA - Honolulu (UTC-10:00)" },
  { value: "America/Toronto", label: "Canada - Toronto (UTC-05:00)" },
  { value: "America/Montreal", label: "Canada - Montreal (UTC-05:00)" },
  { value: "America/Edmonton", label: "Canada - Edmonton (UTC-07:00)" },
  { value: "America/Vancouver", label: "Canada - Vancouver (UTC-08:00)" },
  { value: "America/Mexico_City", label: "Mexico - Mexico City (UTC-06:00)" },

  // Central & South America
  { value: "America/Panama", label: "Panama - Panama City (UTC-05:00)" },
  { value: "America/Costa_Rica", label: "Costa Rica - San José (UTC-06:00)" },
  { value: "America/Havana", label: "Cuba - Havana (UTC-05:00)" },
  { value: "America/Bogota", label: "Colombia - Bogota (UTC-05:00)" },
  { value: "America/Lima", label: "Peru - Lima (UTC-05:00)" },
  { value: "America/Santiago", label: "Chile - Santiago (UTC-04:00)" },
  { value: "America/Sao_Paulo", label: "Brazil - Sao Paulo (UTC-03:00)" },
  { value: "America/Buenos_Aires", label: "Argentina - Buenos Aires (UTC-03:00)" },
  { value: "America/Montevideo", label: "Uruguay - Montevideo (UTC-03:00)" },
  { value: "America/Asuncion", label: "Paraguay - Asunción (UTC-04:00)" },

  // Africa
  { value: "Africa/Cairo", label: "Egypt - Cairo (UTC+02:00)" },
  { value: "Africa/Casablanca", label: "Morocco - Casablanca (UTC+01:00)" },
  { value: "Africa/Accra", label: "Ghana - Accra (UTC±00:00)" },
  { value: "Africa/Lagos", label: "Nigeria - Lagos (UTC+01:00)" },
  { value: "Africa/Addis_Ababa", label: "Ethiopia - Addis Ababa (UTC+03:00)" },
  { value: "Africa/Nairobi", label: "Kenya - Nairobi (UTC+03:00)" },
  { value: "Africa/Johannesburg", label: "South Africa - Johannesburg (UTC+02:00)" },

  // Australia & Oceania
  { value: "Australia/Perth", label: "Australia - Perth (UTC+08:00)" },
  { value: "Australia/Adelaide", label: "Australia - Adelaide (UTC+09:30)" },
  { value: "Australia/Melbourne", label: "Australia - Melbourne (UTC+10:00)" },
  { value: "Australia/Sydney", label: "Australia - Sydney (UTC+10:00)" },
  { value: "Australia/Brisbane", label: "Australia - Brisbane (UTC+10:00)" },
  { value: "Pacific/Guam", label: "Guam (UTC+10:00)" },
  { value: "Pacific/Port_Moresby", label: "Papua New Guinea - Port Moresby (UTC+10:00)" },
  { value: "Pacific/Auckland", label: "New Zealand - Auckland (UTC+12:00)" },
  { value: "Pacific/Fiji", label: "Fiji (UTC+12:00)" },
];