import api from "./axios";

export type AdminVerificationCapture = { challengeIndex: number; challengeType: string; viewPath: string };
export type AdminVerificationRequestStatus = "PENDING" | "PROCESSING" | "ADMIN_REVIEW_REQUIRED" | "APPROVED" | "REJECTED" | "EXPIRED";
export type AdminVerificationJobStatus = "PENDING" | "RUNNING" | "RETRY_WAIT" | "COMPLETED" | "FAILED";
export type AdminVerificationDetail = { account: { userReference: string; email: string; status: string; role: string }; profile: { profileReference: string; username: string; realName: string | null; dateOfBirth: string; mobileCountryCode: string | null; mobileNumber: string | null; country: string | null; city: string | null; languages: string[]; bio: string; interests: string[]; profileStatus: string; verificationSubmissionVersion: number; verificationSubmittedAt: string | null; rejectionReason: string | null; avatar: string; cover: string; profilePhotos: string[] }; verificationRequest: { verificationReference: string; status: AdminVerificationRequestStatus; attemptNumber: number; profileSubmissionVersion: number; submittedAt: string; processingStartedAt: string | null; adminReviewRequiredAt: string | null; adminReviewReasonCode: string | null; adminReviewReason: string | null; decisionAuthority: "AI" | "ADMIN" | null; decidedAt: string | null; decision: string | null; decisionReason: string | null; expiredAt: string | null; aiDecisionSnapshot: { source: "AI"; model: { identifier: string; version: string }; similarity: number; threshold: number; decidedAt: string } | null }; job: { status: AdminVerificationJobStatus; attemptCount: number; maxRetryCount: number; completedAt: string | null; failedAt: string | null; lastErrorCode: string | null } | null; faceSession: { sessionReference: string; profileSubmissionVersion: number; status: string; isCurrent: boolean; requiredCaptureCount: number; acceptedCaptureCount: number; challenges: string[]; startedAt: string; captureCompletedAt: string | null; invalidatedAt: string | null }; captures: AdminVerificationCapture[]; shadowIdentityAnalysis: { status: "NOT_CONFIGURED" | "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED"; conclusion: "LIKELY_MATCH" | "LIKELY_MISMATCH" | "UNABLE_TO_DETERMINE" | null; similarity: number | null; threshold: number | null; model: { identifier: string; version: string } | null; processedAt: string | null; usableCaptureCount: number | null; reasonCode: string | null; reason: string | null } };
export const getAdminVerificationDetail = async (reference: string) => (await api.get<{ verification: AdminVerificationDetail }>(`/v1/admin/profile-verification/${encodeURIComponent(reference)}`)).data.verification;
const relativeApiPath = (viewPath: string) => {
  const baseUrl = String(api.defaults.baseURL ?? "").replace(/\/$/, "");
  const apiPath = new URL(baseUrl, window.location.origin).pathname.replace(/\/$/, "");
  return viewPath.startsWith(`${apiPath}/`) ? viewPath.slice(apiPath.length) : viewPath;
};
export const getAdminVerificationCapture = async (viewPath: string) => (await api.get(relativeApiPath(viewPath), { responseType: "blob" })).data as Blob;
